### PR TITLE
Improve the redeploy feature

### PR DESCRIPTION
**Pull request by cescoffier**
Integrate an `Initialize` mojo collecting all the mojo executed before the redeployment. Upon changes in `src/main`, it replays the executions (only the ones from [compile .. process-classes].

### CODE REVIEW

**Comment by cescoffier** [comment]
The PR alos updates the samples. The web sample is not recompiling Less files on the fly.

**Comment by cescoffier** [comment]
This PR also fixes #27: if the extend plugin runs in the right Maven phase, its execution is replayed. 

However, also notice that ALL mojos are re-executed, including the ones not impacted by the file change. It is impossible to associate (at runtime) the file type to the mojo.

**Comment by cescoffier** [comment]
This PR paves the road to the usage of the Frontend Maven plugin to handle JavaScript dependencies (and so relates to #21).

**Comment by cescoffier** [comment]
Extend the web example to demonstrate:

* integration of the simple compiler plugin (Less)
* integration of the frontend maven plugin
* integration of JS dependencies (bower)
* integration of a grunt build (for coffeeescript in this example)

**Comment by kameshsampath** [comment]
[merge]

**Pull request merged**
